# MDP Topology Optimizer Configuration
# This file contains all configuration parameters for the topology optimization system

# Q-Learning Parameters
q_learning:
  episodes: 100
  learning_rate: 0.8
  gamma: 0.95
  epsilon_decay: 0.05
  max_steps: 15
  epsilon_min: 0.1
  epsilon_max: 1.0

# Genetic Algorithm Parameters (DEAP)
genetic_algorithm:
  population_size: 100
  generations: 50
  crossover_prob: 0.8
  mutation_prob: 0.1
  tournament_size: 3
  elitism_ratio: 0.1

# Environment Parameters
environments:
  synrm:
    grid_sizes: [6, 7, 8, 9, 10]
    max_flux_barriers: 3
    min_flux_barrier_width: 1
    rotor_outer_diameter: 100
    rotor_inner_diameter: 50
    max_material_usage: 0.7

  ccore:
    grid_sizes: [3, 4, 5]
    core_width: 20
    core_height: 30
    air_gap: 2
    max_material_usage: 0.7

# Physics Simulation Parameters
physics:
  synrm:
    saliency_weight: 0.4
    torque_weight: 0.4
    efficiency_weight: 0.2
    connectivity_threshold: 0.6

  ccore:
    connectivity_weight: 0.5
    field_concentration_weight: 0.3
    material_efficiency_weight: 0.2
    min_connected_components: 1

# Training Parameters
training:
  save_frequency: 10
  results_dir: "results"
  log_level: "INFO"
  random_seed: 42

# Visualization Parameters
visualization:
  dpi: 150
  figsize: [8, 6]
  colormap: "viridis"
  save_formats: ["png", "pdf"]
  show_plots: true

# Output Parameters
output:
  save_models: true
  save_histories: true
  save_plots: true
  verbose: true
