# Physics-Informed Neural Network Configuration
xpinn:
  layers1: [2, 400, 400, 100, 1]
  layers2: [2, 100, 100, 40, 1]
  mu1: 1
  mu2: 1
  scaling_factor: 20
  multiplier: 20

training:
  max_iter: 25000
  adam_lr: 0.0008
  n_f1: 1000
  n_f2: 200
  n_ub: 500
  n_i1: 250

physics:
  equation: "poisson"  # poisson, helmholtz, etc.
  domain_decomposition: "interface"
