# Deep Learning Configuration
model:
  img_size: [400, 400]
  channels: 1
  architecture: "unet_skip"

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"

data:
  normalization: "minmax"  # minmax, zscore, none
  augmentation: true
